spring:
  jpa:
    hibernate.ddl-auto: create-drop
    database: H2SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: